### ISSUE TITLE
Bi-level optimization problem

### ISSUE THREAD

**Issue by tommasomiori** [TUMCREATE-ESTL/cobmo#2]
This issue is opened to discuss the use of **bi-level optimization** in the storage feature.

**Comment by tommasomiori** [comment]
The 1st working version of the bi-level problem can be found at (98d5444cd7b494ba87d79aa98c2b89366de29d45). 
- This is done with **sensible thermal storage**.
- The objective function is **quadratic**.

Notes for this commit:
- the functioning is made possible by considering some fixed capital investment, meaning CAPEX that does _not_ depend on the storage size. This is set to 100.0 $ (https://github.com/TUMCREATE-ESTL/cobmo/commit/98d5444cd7b494ba87d79aa98c2b89366de29d45#diff-572028650d13831372cb8eb10620b124R236). This number is random but is in line with the capital cost of storage, which is 300$/m3. This fixed CAPEX is then a quite small value.
- The problem looks to work with a quadratic constraint (https://github.com/TUMCREATE-ESTL/cobmo/commit/98d5444cd7b494ba87d79aa98c2b89366de29d45#diff-572028650d13831372cb8eb10620b124R207-R214). The constraint is needed basically to keep the objective above zero.

**Comment by tommasomiori** [comment]
Also this version has the following problem.
**_decreasing the storage efficiency leads to a decrease in payback time, which does not make sense._**

**Comment by stroitzsch** [comment]
@tommasomiori, is this still relevant or can the issue be closed?

**Comment by tommasomiori** [comment]
> @tommasomiori, is this still relevant or can the issue be closed?

You could close the issue but leave the description for future reference.
I will write a description in the next weeks. Does it work?

**Comment by stroitzsch** [comment]
Ok sure, let's keep it open until you write the description!

**Comment by stroitzsch** [comment]
Has been closed due to inactivity.
